### ISSUE TITLE
bounding boxes width not correct with custome vision models !!

### ISSUE THREAD

**Issue by initmahesh** [psakamoori/intel-rrk-custom-vision#4]
with the attached model we have seen that bounding boxes widths is not correct also the bounding boxes outline need can be better...
try this url with coke and pepsi detecter

https://irisprodwu2training.blob.core.windows.net/m-dbbe97976f4941c3b59e5892cc68de52/aff23be56a9549d79cb690c4971bbdd0.ONNX.zip?sv=2017-04-17&sr=b&sig=R2xaujL%2BYzDQmZmzEVQh6VzK6uQRW7IuHkxgyrjUCSY%3D&se=2020-03-11T13%3A03%3A24Z&sp=r

**Comment by psakamoori** [comment]
Pushed fix to master. Let me know, if see any issue
