### ISSUE TITLE
default module does not do any inference due to twin udpate 

### ISSUE THREAD

**Issue by initmahesh** [psakamoori/intel-rrk-custom-vision#5]
After deploying module on a new machine the module does not produce any inference,
Workaround is to set the module twin property with model url,

the issue is that due to periodic update twint he new value od modelzipurl is read as "" and then no model is applied for inference ,,,

**Comment by psakamoori** [comment]
Module now produce default inference with modelzipurl set to "".

Note: When deploying module on new setup - by default with no twin update - App will just render the camera/video stream with no inference running
